import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, AlertTriangle, CalendarDays, ChevronDown, LogOut, RefreshCw, RotateCcw, Server, SlidersHorizontal, Sparkles } from 'lucide-react';
import { Button, FormControl, MenuItem, Select, TextField } from '@mui/material';
import './styles.css';
import './tooltip.css';

const API_BASE = import.meta.env.VITE_API_BASE_URL || 'https://fractaldmsdev.centralindia.cloudapp.azure.com';
const IST = 'Asia/Kolkata';

type Asset = { id: string; name: string; codename?: string | null; assetlevel_id: number; children?: Asset[] };
type Shift = { id: string; code?: string; name: string; shift_timings: string[]; is_active?: boolean };
type Segment = { start_at: string; end_at: string; type: string };
type Count = { bucket_start: string; ok_count: number; ng_count: number };
type Produce = { produce_id?: string; first_seen_ts: string; result: string };
type Data = { runtimes: Segment[]; downtimes: Segment[]; stoppages: Segment[]; produce_counts: Count[]; produces?: { produces: Produce[] }[] };
type Cycle = { bucket_start: string; ideal_cycle_time_seconds: number | null; actual_cycle_time_seconds: number | null };
type User = { name?: string; username: string; email?: string };
type Choice = { id: string; label: string; shift: Shift; index: number };

const empty: Data = { runtimes: [], downtimes: [], stoppages: [], produce_counts: [] };
const token = () => sessionStorage.getItem('pulse_token');

async function api<T>(path: string, init: RequestInit = {}, retry = true): Promise<T> {
  for (let attempt = 0; ; attempt += 1) {
    const response = await fetch(API_BASE + path, {
      ...init,
      headers: { 'Content-Type': 'application/json', ...(token() ? { Authorization: `Bearer ${token()}` } : {}), ...(init.headers || {}) }
    });
    const body = await response.json().catch(() => ({}));
    if (response.status === 401) { sessionStorage.removeItem('pulse_token'); window.dispatchEvent(new Event('expired')); throw Error('Your session has expired.'); }
    if (response.ok && (body.status_code === undefined || body.status_code < 400)) return (body.data ?? body) as T;
    if (response.status >= 500 && retry && attempt < 2) { await new Promise(resolve => setTimeout(resolve, 500 * (attempt + 1))); continue; }
    if (response.status === 403) throw Error('Access denied for this workspace.');
    if (response.status === 422) throw Error(body.message || 'Validation error. Check the selected filters.');
    throw Error(body.message || 'Request failed. Please retry.');
  }
}

function flatten(nodes: Asset[], level = 0): (Asset & { level: number })[] { return (nodes || []).flatMap(node => [{ ...node, level }, ...flatten(node.children || [], level + 1)]); }
function fmtHour(date: Date) { return new Intl.DateTimeFormat('en-IN', { hour: '2-digit', minute: '2-digit', hour12: false, timeZone: IST }).format(date); }
function fmtDate(date: Date) { return new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', year: 'numeric', timeZone: IST }).format(date); }
function istDateTime(date: string, time: string) { return new Date(`${date}T${time}:00+05:30`); }
function windowFor(date: string, choice: Choice) { const starts = [...choice.shift.shift_timings].sort(); const start = starts[choice.index] || starts[0]; const end = starts[(choice.index + 1) % starts.length] || start; const from = istDateTime(date, start); const to = istDateTime(date, end); if (to <= from) to.setUTCDate(to.getUTCDate() + 1); return { from, to, start, end }; }
function shiftChoices(shifts: Shift[]): Choice[] { return shifts.filter(s => s.is_active !== false).flatMap(shift => shift.shift_timings.map((time, index) => ({ id: `${shift.id}-${index}`, label: `${shift.name} · ${time} – ${shift.shift_timings[(index + 1) % shift.shift_timings.length]}`, shift, index }))); }

function Login({ onLogin }: { onLogin: (user: User) => void }) {
  const [username, setUsername] = useState('analytics_user'); const [password, setPassword] = useState('dashboard123'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!username || !password) { setError('Username and password are required.'); return; } setBusy(true); setError(''); try { const result = await api<{ access_token: string }>('/auth/login', { method: 'POST', body: JSON.stringify({ username, password }) }, false); sessionStorage.setItem('pulse_token', result.access_token); onLogin(await api<User>('/auth/me')); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to sign in.'); } finally { setBusy(false); } }
  return <main className="login"><div className="login-visual"><div className="brand"><Activity /> PULSEBOARD</div><div><small>OPERATIONS INTELLIGENCE</small><h1>See every<br /><i>minute</i> of the line.</h1><p>Production rhythm, downtime, and quality signals in one clear view.</p></div><div className="nominal"><span /> SYSTEMS NOMINAL</div></div><form className="login-form" onSubmit={submit}><div className="brand dark"><Activity /> PULSEBOARD</div><small>WELCOME BACK</small><h2>Sign in to your workspace</h2><p>Use your operations credentials to continue.</p><TextField label="Username" value={username} onChange={event => setUsername(event.target.value)} fullWidth margin="normal" /><TextField label="Password" type="password" value={password} onChange={event => setPassword(event.target.value)} fullWidth margin="normal" />{error && <div className="error"><AlertTriangle size={16} />{error}</div>}<Button className="primary" variant="contained" type="submit" disabled={busy}>{busy ? 'Signing in...' : 'Enter dashboard'} <b>→</b></Button><em>Token-based session · protected access</em></form></main>;
}

function Timeline({ data, from, to, show }: { data: Data; from: Date; to: Date; show: boolean }) {
  const canvas = useRef<HTMLCanvasElement>(null); const [range, setRange] = useState<[number, number]>([from.getTime(), to.getTime()]); const [tooltip, setTooltip] = useState<{ x: number; y: number; text: string } | null>(null); const produces = useMemo(() => (data.produces || []).flatMap(bucket => bucket.produces).map(point => ({ ...point, timestamp: new Date(point.first_seen_ts).getTime() })), [data.produces]);
  useEffect(() => setRange([from.getTime(), to.getTime()]), [from, to]);
  useEffect(() => { const element = canvas.current; if (!element) return; const box = element.getBoundingClientRect(); const ratio = window.devicePixelRatio || 1; element.width = box.width * ratio; element.height = box.height * ratio; const ctx = element.getContext('2d'); if (!ctx) return; ctx.scale(ratio, ratio); const [start, end] = range; const x = (time: number) => ((time - start) / (end - start)) * box.width; ctx.fillStyle = '#f4f7f5'; ctx.fillRect(0, 0, box.width, box.height);
    const bands = [...data.runtimes.map(segment => ({ ...segment, color: segment.type.includes('unplanned') ? '#b7cf32' : '#22a69b', label: segment.type.includes('unplanned') ? 'UNPLANNED' : 'RUNTIME' })), ...data.downtimes.map(segment => ({ ...segment, color: '#ff755f', label: 'UNKNOWN' })), ...data.stoppages.map(segment => ({ ...segment, color: '#6854ba', label: 'STOPPAGE' }))];
    bands.forEach(segment => { const left = Math.max(0, x(new Date(segment.start_at).getTime())); const right = Math.min(box.width, x(new Date(segment.end_at).getTime())); if (right <= left) return; ctx.fillStyle = segment.color; ctx.fillRect(left, 42, Math.max(2, right - left), 112); if (right - left > 50) { ctx.save(); ctx.translate(left + 9, 70); ctx.rotate(Math.PI / 2); ctx.fillStyle = '#fff'; ctx.font = 'bold 10px sans-serif'; ctx.fillText(segment.label, 0, 0); ctx.restore(); } });
    const max = Math.max(1, data.produce_counts.reduce((sum, count) => sum + count.ok_count + count.ng_count, 0)); let total = 0; ctx.strokeStyle = '#2061df'; ctx.lineWidth = 2; ctx.beginPath(); data.produce_counts.forEach((count, index) => { total += count.ok_count + count.ng_count; const px = x(new Date(count.bucket_start).getTime()); const py = 154 - total / max * 105; index ? ctx.lineTo(px, py) : ctx.moveTo(px, py); ctx.stroke(); ctx.fillStyle = '#2061df'; ctx.beginPath(); ctx.arc(px, py, 3, 0, Math.PI * 2); ctx.fill(); ctx.beginPath(); });
    if (show) produces.forEach((point, index) => { const px = x(point.timestamp); if (px < 0 || px > box.width) return; ctx.fillStyle = point.result === 'FAIL' ? '#fa493c' : '#2161df'; ctx.beginPath(); ctx.arc(px, 145 - (index % 35) * 1.5, 2, 0, Math.PI * 2); ctx.fill(); });
    ctx.strokeStyle = '#25312d'; ctx.beginPath(); ctx.moveTo(0, 174); ctx.lineTo(box.width, 174); ctx.stroke(); ctx.fillStyle = '#62706a'; ctx.font = '11px sans-serif'; for (let index = 0; index <= 6; index += 1) { const time = start + (end - start) * index / 6; ctx.fillText(fmtHour(new Date(time)), x(time) - 16, 194); }
  }, [data, from, to, range, show, produces]);
  const dragStart = useRef<number | null>(null); function mouseMove(event: React.MouseEvent) { if (!show || !produces.length || !canvas.current) return; const box = canvas.current.getBoundingClientRect(); const time = range[0] + ((event.clientX - box.left) / box.width) * (range[1] - range[0]); let nearest = produces[0]; produces.forEach(point => { if (Math.abs(point.timestamp - time) < Math.abs(nearest.timestamp - time)) nearest = point; }); if (Math.abs(nearest.timestamp - time) < (range[1] - range[0]) / box.width * 12) setTooltip({ x: event.clientX - box.left + 12, y: event.clientY - box.top - 42, text: `${fmtDate(new Date(nearest.timestamp))} ${fmtHour(new Date(nearest.timestamp))} · ${nearest.result}` }); else setTooltip(null); }
  return <><div className="chart-label"><span>CUMULATIVE PRODUCTION</span><div><i className="c-run" /> Runtime <i className="c-un" /> Unplanned <i className="c-unk" /> Unknown <i className="c-stop" /> Stoppage</div></div><div className="canvas"><canvas ref={canvas} onMouseMove={mouseMove} onMouseLeave={() => setTooltip(null)} onMouseDown={event => { dragStart.current = event.nativeEvent.offsetX; }} onMouseUp={event => { if (dragStart.current === null || !canvas.current) return; const width = canvas.current.clientWidth; const left = Math.min(dragStart.current, event.nativeEvent.offsetX); const right = Math.max(dragStart.current, event.nativeEvent.offsetX); if (right - left > 12) setRange([range[0] + left / width * (range[1] - range[0]), range[0] + right / width * (range[1] - range[0])]); dragStart.current = null; }} onDoubleClick={() => setRange([from.getTime(), to.getTime()])} />{tooltip && <div className="chart-tooltip" style={{ left: tooltip.x, top: tooltip.y }}>{tooltip.text}</div>}</div><div className="chart-foot"><span>Drag across chart to zoom · double-click to reset</span><span>{show ? `${produces.length.toLocaleString()} individual points` : 'Hourly production counts'}</span><button className="icon" onClick={() => setRange([from.getTime(), to.getTime()])} title="Reset zoom"><RotateCcw size={15} /></button></div></>;
}

function Summary({ data, cycles, from, to }: { data: Data; cycles: Cycle[]; from: Date; to: Date }) {
  const hours: Date[] = []; for (let cursor = new Date(from); cursor < to; cursor.setUTCHours(cursor.getUTCHours() + 1)) hours.push(new Date(cursor));
  const minutes = (segment: Segment, hour: Date) => { const hourEnd = new Date(hour); hourEnd.setUTCHours(hourEnd.getUTCHours() + 1); return Math.max(0, (Math.min(new Date(segment.end_at).getTime(), hourEnd.getTime()) - Math.max(new Date(segment.start_at).getTime(), hour.getTime())) / 60000); };
  function value(row: string, hour: Date) { if (hour.getTime() > Date.now()) return ''; const hourEnd = hour.getTime() + 3600000; if (row === 'Total' || row === 'Pass' || row === 'Fail') return String(data.produce_counts.filter(count => { const time = new Date(count.bucket_start).getTime(); return time >= hour.getTime() && time < hourEnd; }).reduce((sum, count) => sum + (row === 'Total' ? count.ok_count + count.ng_count : row === 'Pass' ? count.ok_count : count.ng_count), 0)); if (row.includes('Cycle')) { const cycle = cycles.find(item => new Date(item.bucket_start).getTime() === hour.getTime()); const number = row.startsWith('Ideal') ? cycle?.ideal_cycle_time_seconds : cycle?.actual_cycle_time_seconds; return number == null ? '' : `${number % 1 ? number.toFixed(1) : number}s`; } const segments = row === 'Runtime' ? data.runtimes : row === 'Unplanned Production' ? data.runtimes.filter(segment => segment.type.includes('unplanned')) : row === 'Stoppage' ? data.stoppages : data.downtimes.filter(segment => segment.type === 'unknown'); return segments.reduce((sum, segment) => sum + minutes(segment, hour), 0).toFixed(1); }
  const rows = ['Total', 'Pass', 'Fail', 'Runtime', 'Unplanned Production', 'Stoppage', 'Unknown Downtime', 'Ideal Cycle Time', 'Actual Cycle Time']; return <section className="summary"><div className="section-head"><div><small>SHIFT TELEMETRY</small><h2>Hourly production & downtime</h2></div><span>● IST · {fmtDate(from)}</span></div><div className="table-scroll"><table><thead><tr><th>Metric</th>{hours.map(hour => <th key={hour.toISOString()}>{fmtHour(hour)}<br /><small>– {fmtHour(new Date(hour.getTime() + 3600000))}</small></th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={row} className={index < 3 ? 'strong' : ''}><th>{row}</th>{hours.map(hour => <td key={hour.toISOString()}>{value(row, hour)}{['Runtime', 'Unplanned Production', 'Stoppage', 'Unknown Downtime'].includes(row) && <small> min</small>}</td>)}</tr>)}</tbody></table></div></section>;
}

function Dashboard({ user, logout }: { user: User; logout: () => void }) {
  const [assets, setAssets] = useState<(Asset & { level: number })[]>([]); const [choices, setChoices] = useState<Choice[]>([]); const [assetId, setAssetId] = useState(''); const [choiceId, setChoiceId] = useState(''); const [date, setDate] = useState('2026-06-23'); const [show, setShow] = useState(false); const [data, setData] = useState<Data>(empty); const [cycles, setCycles] = useState<Cycle[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const asset = assets.find(item => item.id === assetId); const choice = choices.find(item => item.id === choiceId) || choices[0]; const window = asset && choice ? windowFor(date, choice) : null;
  async function load() { if (!asset || !choice || !window) return; setLoading(true); setError(''); try { const base = { entity_scope: { type: 'asset', asset: { asset_id: asset.id, asset_level_id: asset.assetlevel_id } }, time_range: { from_ts: window.from.toISOString(), to_ts: window.to.toISOString() } }; const [intervals, hourly] = await Promise.all([api<Data>('/analytics-query/machine-intervals', { method: 'POST', body: JSON.stringify({ ...base, produce_counts: true, exact_produces: show, group_produce_counts_by_part_model: true }) }), api<Cycle[]>('/analytics-query', { method: 'POST', body: JSON.stringify({ ...base, metrics: ['ideal_cycle_time_seconds', 'actual_cycle_time_seconds'], distribution: 'hourly' }) })]); setData(intervals); setCycles(hourly); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load telemetry.'); } finally { setLoading(false); } }
  useEffect(() => { Promise.all([api<Asset[]>('/core/assets/tree'), api<Shift[]>('/core/shifts')]).then(([tree, shifts]) => { const flat = flatten(tree); const nextChoices = shiftChoices(shifts); setAssets(flat); setChoices(nextChoices); setAssetId(flat[0]?.id || ''); setChoiceId(nextChoices[0]?.id || ''); }).catch(reason => setError(reason instanceof Error ? reason.message : 'Unable to load filters.')); }, []);
  useEffect(() => { if (asset && choice) load(); }, [assetId, choiceId, date, show]);
  return <main className="app"><header><div className="brand dark"><Activity /> PULSEBOARD <span>/ OPERATIONS</span></div><div className="top"><span className="connected">● Connected</span><div className="avatar">{(user.name || user.username)[0]}</div>{user.name || user.username}<button className="icon" onClick={logout} title="Log out"><LogOut size={17} /></button></div></header><div className="content"><div className="intro"><div><small>PRODUCTION CONTROL CENTER</small><h1>Timeline overview</h1><p>One shift, every signal in context.</p></div>{window && <div className="date"><CalendarDays size={16} /> {fmtDate(window.from)} → {fmtDate(window.to)}</div>}</div><section className="filters"><div><label>Asset / line</label><FormControl fullWidth size="small"><Select value={assetId} onChange={event => setAssetId(event.target.value)} startAdornment={<Server size={15} />}>{assets.map(item => <MenuItem key={item.id} value={item.id}>{item.name} · {item.codename || item.assetlevel_id}</MenuItem>)}</Select></FormControl></div><div><label>Date</label><TextField type="date" size="small" value={date} onChange={event => setDate(event.target.value)} fullWidth /></div><div><label>Shift window</label><FormControl fullWidth size="small"><Select value={choiceId} onChange={event => setChoiceId(event.target.value)} startAdornment={<SlidersHorizontal size={15} />}>{choices.map(item => <MenuItem key={item.id} value={item.id}>{item.label}</MenuItem>)}</Select></FormControl></div><div className="togglebox"><label>Individual produces</label><button className={`toggle ${show ? 'on' : ''}`} onClick={() => setShow(value => !value)} aria-pressed={show}><span /></button><small>{show ? 'On · detailed points' : 'Off · hourly counts'}</small></div><Button className="refresh" variant="contained" onClick={load} disabled={loading}>{loading ? 'Loading...' : <><RefreshCw size={16} /> Refresh</>}</Button></section>{error && <div className="error banner"><AlertTriangle size={16} />{error}<button onClick={load}>Retry</button></div>}<section className="panel"><div className="section-head"><div><small>{asset?.name?.toUpperCase() || 'TELEMETRY'}</small><h2>Production history</h2></div><div className="kpis"><b>{data.produce_counts.reduce((sum, item) => sum + item.ok_count, 0)}</b> pass <b className="fail">{data.produce_counts.reduce((sum, item) => sum + item.ng_count, 0)}</b> fail</div></div>{window && <Timeline data={data} from={window.from} to={window.to} show={show} />}{!loading && !data.runtimes.length && !data.produce_counts.length && <div className="empty">No telemetry for this shift. Try another date or refresh.</div>}</section>{window && <Summary data={data} cycles={cycles} from={window.from} to={window.to} />}<footer><Sparkles size={14} /> Built for clear decisions on the floor · Data shown in IST</footer></div></main>;
}

function App() { const [user, setUser] = useState<User | null>(null); const [checking, setChecking] = useState(true); useEffect(() => { const expired = () => setUser(null); window.addEventListener('expired', expired); (async () => { if (token()) { try { setUser(await api<User>('/auth/me')); } catch { /* session event handles expiry */ } } setChecking(false); })(); return () => window.removeEventListener('expired', expired); }, []); if (checking) return <div className="splash"><Activity /> Loading workspace...</div>; if (!user) return <Login onLogin={setUser} />; return <Dashboard user={user} logout={async () => { try { await api('/auth/logout', { method: 'POST' }); } catch { /* local logout still wins */ } sessionStorage.removeItem('pulse_token'); setUser(null); }} />; }
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
